{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eidolon.secretName" . }}
  labels:
    {{- include "eidolon.labels" . | nindent 4 }}
type: Opaque
stringData:
  EIDOLON_ADMIN_TOKEN: {{ .Values.secrets.adminToken | quote }}
  EIDOLON_AUDIT_TOKEN: {{ .Values.secrets.auditToken | quote }}
  EIDOLON_DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  EIDOLON_OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret | quote }}
{{- end }}
